name: Credential Warning

on:
  push:
    branches: [ master ]
  
jobs:
  RemoveCredentials:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v1

    # Runs a single command using the runners shell
    - name: CheckCredentials
      id: checkCreds
      uses: andstor/file-existence-action@v1
      with:
        files: "credentials"
    
    -name: CredentialWarning
      if: steps.checkCreds.outputs.files_exists == 'true'
      run: echo There are credentials stored. Remove them!
